DAL layer for user entity
Alexey-beercode/OnlineShop pull request #3
Opened 2024-06-18 19:12 UTC by KiSSel3

- Created user entity
- Added interface and its implementation for working with users table
- Created validator for key user fields

2024-06-18 19:16 UTC, KiSSel3 commented
- Added a .idea folder to .gitignore

2024-06-18 19:23 UTC, mebry requested changes

2024-06-18 19:23 UTC, mebry commented on OnlineShop/OnlineShop.DAL/Validators/UserValidator.cs
> +public class UserValidator : AbstractValidator<User>
Remove the validators from this layer. They should be on the BLL layer

2024-06-18 19:23 UTC, mebry commented on OnlineShop/OnlineShop.DAL/Repositories/Implementations/UserRepository.cs
> +    public async Task<User> GetById(Guid id)
For asynchronous methods, pass CancellationToken and use it

2024-06-18 19:23 UTC, mebry commented on OnlineShop/OnlineShop.DAL/Repositories/Implementations/UserRepository.cs
> +    public async Task<User> GetById(Guid id)
Always add the suffix "Async" to the names of methods that have an Async or async modifie

2024-06-18 19:23 UTC, mebry commented on OnlineShop/OnlineShop.DAL/Repositories/Implementations/UserRepository.cs
> +        var user = await dbContext.Users.SingleOrDefaultAsync(u => u.Id.Equals(id));
Can be simplified

2024-06-19 07:50 UTC, mebry approved these changes

2024-06-19 07:53 UTC, merged