BLL layer for user entity
Alexey-beercode/OnlineShop pull request #8
Opened 2024-06-19 19:55 UTC by KiSSel3

- Created user dto
- Added UserService interface and implementation
- Validators have been created for user dto
- Configured mapper for user dto

2024-06-20 16:16 UTC, mebry requested changes

2024-06-20 16:16 UTC, mebry commented on OnlineShop/OnlineShop.BLL/Mappers/MapsterConfig.cs
> +            .Map(dest => dest.PasswordHash, src => PasswordHelper.HashPassword(src.Password))
This call must take place inside the service:PasswordHelper.HashPassword(src.Password)

2024-06-20 16:16 UTC, mebry commented on OnlineShop/OnlineShop.BLL/Mappers/MapsterConfig.cs
> +            .MapWith(src => StringToGuidMapper.ToString(src));
I don't understand why you need this. just call inside the services and that's it

2024-06-20 16:16 UTC, mebry commented on OnlineShop/OnlineShop.BLL/Mappers/MapsterConfig.cs
> +            .Map(dest => dest.IsDeleted, src => false);
why should this field be set like this?

2024-06-20 16:16 UTC, mebry commented on OnlineShop/OnlineShop.BLL/Mappers/StringToGuidMapper.cs
> +            throw new MappingException($"The string '{value}' is not a valid Guid.");
This is not an exception to mapping, but to converting values

2024-06-20 16:16 UTC, mebry commented on OnlineShop/OnlineShop.BLL/Mappers/StringToGuidMapper.cs
> +    }
Why do you need this

2024-06-20 16:16 UTC, mebry commented on OnlineShop/OnlineShop.BLL/Services/Implementations/UserService.cs
> +        MapsterConfig.Configure();
The configuration can be moved outside of this class and registered where the di registration takes place

2024-06-20 16:16 UTC, mebry commented on OnlineShop/OnlineShop.BLL/Services/Implementations/UserService.cs
> +        var id = userId.Adapt<Guid>();
redo

2024-06-20 16:16 UTC, mebry commented on OnlineShop/OnlineShop.BLL/Services/Implementations/UserService.cs
> +        LoginValidator loginValidator = new LoginValidator();
use var here

2024-06-20 16:16 UTC, mebry commented on OnlineShop/OnlineShop.BLL/Services/Implementations/UserService.cs
> +        await loginValidator.ValidateAndThrowAsync(loginRequestDTO, cancellationToken);
And why do you need to create a validator in general, you can use auto-validation

2024-06-20 16:16 UTC, mebry commented on OnlineShop/OnlineShop.BLL/Services/Implementations/UserService.cs
> +        await registerValidator.ValidateAndThrowAsync(registerRequestDTO, cancellationToken);
the same

2024-06-20 18:55 UTC, KiSSel3 commented
Corrected errors

2024-06-22 09:40 UTC, mebry approved these changes

2024-06-23 12:56 UTC, merged